{
 "title": "Graph_DB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "subgraph_deployment_detail",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT sd.vid,sd.id,sd.network,sd.health,sd.node_id,sd.failed,sd.synced,sd.entity_count,sm.description,sm.repository,sd.latest_ethereum_block_number,sd.ethereum_head_block_number FROM subgraphs.\"subgraph_deployment_detail\" as sd left join subgraphs.\"subgraph_manifest\" sm on (sm.id = sd.manifest) order by sd.vid"
    }
   ]
  },
  {
   "title": "CostModels",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM public.\"CostModels\""
    }
   ]
  },
  {
   "title": "IndexingRules",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ir.deployment,ir.\"allocationAmount\", ir.\"parallelAllocations\", ir.\"maxAllocationPercentage\", ir.\"minSignal\", ir.\"minStake\", ir.\"maxSignal\", ir.\"minAverageQueryFees\", ir.\"custom\", ir.\"decisionBasis\", ir.\"createdAt\", ir.\"updatedAt\" \n\nFROM public.\"IndexingRules\" ir"
    }
   ]
  },
  {
   "title": "subgraph_error",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM subgraphs.\"subgraph_error\" "
    }
   ]
  },
  {
   "title": "deployment_schemas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM public.\"deployment_schemas\""
    }
   ]
  },
  {
   "title": "tables",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM information_schema.tables"
    }
   ]
  },
  {
   "title": "ethereum_blocks",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT count(hash) \"count\", max(number) as \"max_number\", network_name FROM public.\"ethereum_blocks\" GROUP BY network_name"
    }
   ]
  },
  {
   "title": "ethereum_networks",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM\n  ethereum_networks\n  limit 5\n"
    }
   ]
  }
 ]
}